# 错误的处理

上一小节我们介绍了前端的四种错误类型。对于这四种错误呢，对于它们的处理方式也各不相同。

## 处理未捕获的错误

对于在应用程序中未捕获的错误，我们可以利用 JavaScript 的全局错误处理机制来捕获并处理这些错误。具体来说，我们可以使用 `window.addEventListener` 方法来添加一个全局的 `error` 事件监听器。

```tsx
window.addEventListner("error", (error) => {
  consle.log("error", error);
});
```

值得注意的是，虽然这种全局错误处理机制可以捕获到大部分的运行时错误，但是对于已经被 `try catch` 捕捉的错误，除非再次抛出，否则是无法监听到的

```tsx
try {
  throw new Error("error");
} catch (error) {
  console.log("error", error); // 无法捕捉
}
```

此外，对于在控制台的输出，也是无法捕捉的

```tsx
consle.log("error", new Error("error")); // 无法捕捉
```

如果想要捕捉在控制台中输出的错误，我们需要使用“猴子补丁”技术。

> "猴子补丁"（Monkey Patching）是指在运行时动态修改类或模块，而不改动源码。这种技术常常用于在运行时对程序行为进行修改，或者修复库、模块中的错误。然而，猴子补丁应该谨慎使用，因为它可能会导致代码的行为难以预测，并可能会引入新的错误。

```tsx
const originalConsoleLog = console.log;

// 使用自定义的函数替换 console.log
console.log = function (...messages) {
  setTimeout(() => {
    for (const message of messages) {
      if (message instanceof Error) {
        throw message;
      }
    }
  }, 0);

  // 调用原始的 console.log 方法
  originalConsoleLog.apply(console, messages);
};
```

## 处理未捕获的 Promise 错误

当 `Promise` 被 `reject` 且没有对应的错误处理器（即 `.catch` 或 `try...catch` 块）时，就会触发 `unhandledrejection` 事件。这种情况下，我们可以通过监听 `unhandledrejection` 事件来全局捕获并处理这些未被捕获的 `Promise` 错误。

```tsx
window.addEventListener("unhandledrejection", (error) => {
  console.log("error", error);
});
```

我们在上一小节提到过，下面的代码不会抛出错误，因为 `Promise`的 `reject` 状态已经被处理了。

```tsx
const rejectedPromise = Promise.reject(new Error("error"));

rejectedPromise.catch(() => {});
```

但是...，如果我们加一个 `setTimeout` 呢？

```tsx
const rejectedPromise = Promise.reject(new Error("error"));

setTimeout(() => {
  rejectedPromise.catch(() => {});
}, 2000);
```

答案是： 此时的 rejectedPromise 会被 `unhandledrejection` 事件捕捉到，因为这个 `Promise` 对象没有当前的宏任务中立即被处理。并且，在下一个宏任务中处理了之后，还会触发 `rejectionhandled` 事件，表示这个 `Promise对象` 虽然以前被 `reject` 了，但是现在被处理了，（因为它现在被处理了），你可能需要处理它。

## 处理网络请求错误

处理网络请求错误是开发过程中的一项重要任务，尤其是在处理 `fetch` 或 `xhr` 请求时。这一任务的挑战性在于没有任何事件能直接监听到这些请求的错误。

遗憾的是，我们并没有直接的方法来全局监听 `fetch` 或 `xhr` 的错误。这可能会让我们在处理网络错误时感到无所适从。

然而，我们在开发应用时，还是有一些策略可以采取。一种常见的做法是使用 `try-catch` 语句来包裹我们的网络请求。这样，当请求出现错误时，我们可以捕捉到这个错误，并设定一个默认值来处理这个错误。这种方法虽然不能全局捕获错误，但是可以在特定的网络请求中处理错误。

最后，有一种更为全局的方法可以捕捉网络请求错误，那就是使用猴子补丁 (Monkey Patching)。我们可以通过猴子补丁来重写原生的 `fetch` 或 `xhr` 函数。这样，每当发出一个网络请求时，我们就可以在请求过程中插入我们自己的错误处理代码。这种方法虽然比较复杂，但是它可以让我们全局捕捉和处理网络请求错误，从而让我们的应用更加健壮和可靠。

```tsx
// 重写fetch
const originalFetch = window.fetch;

window.fetch = async (...args) => {
  return originalFetch.apply(window, args).then(
    (response) => {
      return response;
    },
    (error) => {
      throw error;
    }
  );
};
```

## 处理资源加载错误

处理资源的加载错误也可以使用我们的 `error` 事件监听，但由于资源加载失败的错误不会冒泡，我们需要在事件的捕获阶段去监听。

```tsx
document.body.addEventListener(
  "error",
  (event) => {
    if (!event.target) return;

    if (event.target.tagName === "IMG") {
      console.log(`Failed to load image: ${event.target.src}`, "warning");
    } else if (event.target.tagName === "LINK") {
      console.log(`Failed to load css: ${event.target.href}`, "warning");
    }
  },
  { capture: true } // 捕获阶段监听
);
```

测试一下，我们会发现已经可以监听到图片资源的加载失败了

```tsx
const image = document.createElement('img');
image.src = "http://dassdas/dassd.png";
document.body.appendChild(image)
```